### ISSUE TITLE
Improve generator

### ISSUE THREAD

**Issue by VictorKoenders** [Trangar/periodic_table#1]
- [ ] Move src/main.rs to src/bin/generate.rs
- [ ] Move the generated file to src/generated.rs
- [ ] Parse the CSV directly into a CsvElement type that implements Debug to generate Element code
- [ ] Introduce lazy_static!

**Comment by VictorKoenders** [comment]
09:13:09 < Xion_> https://github.com/Trangar/periodic_table/blob/master/src/main.rs#L89 -- You could wrap the Vec<String> in a newtype and implement Display/Debug on it, it'd give you
          access to .debug_struct which is nicer than manual formating of struct decls
09:14:05 < Trangar> Is debug_struct guaranteed to be compileable code?
09:14:20 < Xion_> I think so?
09:15:39 < Xion_> The other obvious thing you could do is introduce more types rather than using strings everywhere
09:15:43 < Xion_> E.g. for atomic mass
09:15:59 < Trangar> The obvious thing would be to just parse the CSV directly to an object that implements Deserialize
09:16:12 < Trangar> And then implement Debug for that that generates the proper code
09:16:21 < Xion_> +1 that's a good idea
09:16:42 < Xion_> It could even be the Element type :D
09:16:51 < Trangar> CsvElement or something

**Comment by Xion** [comment]
‹Xion_›  You probably also want to add docs on every field :) E.g. melting/boilingPoint need a reference pressure
‹Xion_›  (and probably an enum rather than Option, because there are three states: Unknown, Known(u32), NotApplicable in case of helium)

**Comment by VictorKoenders** [comment]
(Mostly) closed in #4, #5 and #6 (thanks @noirotm!)
